name: SigLib
channels:
- conda-forge
- defaults
dependencies:
  - python=3.6
  - GDAL=2.3.3
  - postgresql
  - scipy
  - future
  - psycopg2
  - numpy
  - configparser
  - snappy
  - pip
  - pip:
    - ctypes_snappy


    